---
- hosts: linux-manager
  vars:
    db_ip: 192.168.126.200
    db_port: 5432
    db_id: unity
    db_pwd: 1111
    db_name: omniguard
    db_ssl: n
    was_ip: 192.168.126.200
    was_port: 8080
    was_id: admin
    was_pwd: admin
    was_ssl: n
    unity_ver: 5.0-125
  tasks:
    - name: find unity manager install files
      find:
        path: /root
        patterns: lsware-*.*
      register: lsware_files_to_delete

    - name: delete unity manager install files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ lsware_files_to_delete.files }}"

    - name: delete /opt/src (unity package source directory)
      file:
        path: /opt/src
        state: absent

    - name: Install the libselinux-python package
      yum: name=libselinux-python state=present

    - name: Disable SELinux
      selinux: state=disabled

    - name: copy unity manager rpm file with owner and permissions
      copy:
        src: /root/rpms/lsware-unityx-manager-{{unity_ver}}-linux-2.6-x86_64.rpm.gz
        dest: /root/lsware-unityx-manager-{{unity_ver}}-linux-2.6-x86_64.rpm.gz
        owner: root
        group: root
        mode: 0644

    - name: copy unity package tar file with owner and permissions
      copy:
        src: /root/rpms/lsware-unityx-packages-{{unity_ver}}-linux-2.6-x86_64.tar
        dest: /root/lsware-unityx-packages-{{unity_ver}}-linux-2.6-x86_64.tar
        owner: root
        group: root
        mode: 0644

    - name: unzip unity manager rpm.gz file
      shell: gzip -d /root/lsware-unityx-manager-{{unity_ver}}-linux-2.6-x86_64.rpm.gz
      args:
        executable: /bin/bash

    - name: install unity manager rpm from a local file
      yum:
        name: /root/lsware-unityx-manager-{{unity_ver}}-linux-2.6-x86_64.rpm
        state: present

    - name: set registry unity manager
      shell: /opt/lsware/unityx/sbin/unityx registry setmanager {{ansible_host}} {{db_ip}} {{db_port}} {{db_id}} {{db_pwd}} {{db_name}} {{db_ssl}} {{was_ip}} {{was_port}} {{was_ssl}} {{was_id}} {{was_pwd}}
      args:
        executable: /bin/bash

    - name: make unity package directory
      file:
        path: /opt/src
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: untar unity package
      unarchive:
        src: /root/lsware-unityx-packages-{{unity_ver}}-linux-2.6-x86_64.tar
        dest: /opt/src
        remote_src: yes

    - name: sleep for 3 seconds
      wait_for: timeout=3
      delegate_to: localhost

    - name: disribute package files
      shell: /opt/lsware/unityx/sbin/unityx -u admin -p admin distrib publish -d /opt/src/packages/
      args:
        executable: /bin/bash

